name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.Plugin
api-version: 1.14

commands:
  roll:
    description: 引数に入れた整数までの値でランダムな整数を表示
    usage: /<command> [整数]
    default: true

  reflectStatus:
    description: スコアボードにステータスを反映
    usage: /<command>
    default: op