name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.Plugin
api-version: 1.14

commands:
  roll:
    description: 引数で振るダイスを指定\n2つ目の引数にsecretを入れると自分のKPにのみ結果を通知
    usage: 仕様例 /<command> 1d100
    default: true

  reflectStatus:
    description: スコアボードにステータスを反映
    usage: /<command>
    default: op