name: ${project.artifactId}
version: ${project.version}
main: ${project.groupId}.Plugin
api-version: 1.14

commands:
  roll:
    description: roll 1d6
    usage: /<command>
    default: true
    
  setStatus:
    description: ステータスをセット
    usage: /<command>
    default: true