name: TRPG
version: 1.0-SNAPSHOT
main: Rin.TRPG.Ratami.Plugin
api-version: 1.14

commands:
  roll:
    description: 引数で振るダイスを指定.2つ目の引数にsecretを入れると自分のKPにのみ結果を通知
    usage: /<command> 1D100 (secret) 技能名
    default: true

  book:
    description: ステータス設定用本配布コマンド.直接実行することはない
    default: true
    
  statusSet:
    description: ステータス設定用コマンド.直接実行することはない
    default: true

  kp:
    description: コマンド実行者をKPに設定
    usage: /<command> (kpc)
    default: true

  pl:
    description: 実行者をPLに設定&ステータス設定本を配布
    usage: /<command>
    default: true

  change:
    description: オプションのプレイヤーのHP,MP,SANを増やす
    usage: /<command> 対象プレイヤー 対象ステータス 変更値
    default: op

  removeBook:
    description: ステータス振り完了
    usage: /<command>
    default: true

  displayname:
    description: 表示名変更
    usage: /<command> プレイヤー名 表示名
    default: true

  enablepvp:
    description: PvPの可否を設定
    usage: /<command> enable|disable
    default: op

  reflect:
    description: 探索者のステータスをスコアボードとアクションバーに反映
    usage: <command>
    default: true